development:
  :server_name: Nounai
  :attention_minitues: 5
  :db:
    :name: rogv
    :user: hoge
    :pass: piyo
  :auth:
    :key: hogepiyo
    :username: hoge
    :password: piyo
    :delete_key: fizzbuzz
    :sample_mode: false
    :view_mode: false
  :memcache:
    :server: localhost
    :port: 11211
  :use_cache: true
  :admin:
    :user: amistr
    :pass: mohumohu
    :expire_sec: 180
test:
  :server_name: SakrayJ
  :attention_minitues: 5
  :db:
    :name: rogv
    :user: hoge
    :pass: piyo
  :auth:
    :key: hogepiyo
    :username: hoge
    :password: piyo
    :delete_key: fizzbuzz
    :sample_mode: false
    :view_mode: false
  :memcache:
    :server: localhost
    :port: 11211
  :use_cache: false
  :admin:
    :user: amistr
    :pass: mohumohu
    :expire_sec: 600
production:
  :server_name: Gimle
  :app_path: /rogvs
  :attention_minitues: 5
  :db:
    :name: rogv
    :user: hoge
    :pass: piyo
  :auth:
    :key: hogepiyo
    :username: hoge
    :password: piyo
    :delete_key: fizzbuzz
    :sample_mode: false
    :view_mode: false
  :memcache:
    :server: localhost
    :port: 11211
  :use_cache: true
  :admin:
    :user: amistr
    :pass: mohumohu
    :expire_sec: 600
