development:
  :server_name: Nounai
  :attention_minitues: 5
  :db:
    :name: rogv
    :user: hoge
    :pass: piyo
  :auth:
    :key: hogepiyo
    :username: hoge
    :password: piyo
    :delete_key: fizzbuzz
    :sample_mode: false
    :view_mode: false
  :memcache:
    :server: localhost
    :port: 11211
    :header: devel
  :use_cache: true
  :admin:
    :user: amistr
    :pass: mohumohu
    :expire_sec: 180
  :result:
    :recently_size: 6
    :min_size: 4
    :max_size: 12
    :store: false
test:
  :server_name: SakrayJ
  :attention_minitues: 5
  :db:
    :name: rogv
    :user: hoge
    :pass: piyo
  :auth:
    :key: hogepiyo
    :username: hoge
    :password: piyo
    :delete_key: fizzbuzz
    :sample_mode: false
    :view_mode: false
  :memcache:
    :server: localhost
    :port: 11211
    :header: test
  :use_cache: false
  :admin:
    :user: amistr
    :pass: mohumohu
    :expire_sec: 600
  :result:
    :recently_size: 6
    :min_size: 4
    :max_size: 12
    :store: false
production:
  :server_name: Gimle
  :app_path: /rogvs
  :attention_minitues: 5
  :db:
    :name: rogv
    :user: hoge
    :pass: piyo
  :auth:
    :key: hogepiyo
    :username: hoge
    :password: piyo
    :delete_key: fizzbuzz
    :sample_mode: false
    :view_mode: false
  :memcache:
    :server: localhost
    :port: 11211
    :header: hoge
  :use_cache: true
  :admin:
    :user: amistr
    :pass: mohumohu
    :expire_sec: 600
  :result:
    :recently_size: 6
    :min_size: 4
    :max_size: 12
    :store: false
